version: 2.1
jobs:
  build:
    working_directory: ~/browse-everything-redux-react
    docker:
      - image: circleci/node:lts-browsers

    steps:
      - checkout

      # Restore the dependency cache
      - restore_cache:
          keys:
            - yarn-lock-{{ checksum "package-lock.json" }}
            - yarn-lock-
      - run:
          name: Install dependencies with NPM
          command: npm install

      # Save the dependency cache
      - save_cache:
          key: yarn-lock-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      # I kept this commented because it fails
      # - run:
      #     name: Validate the style of the code
      #     command: yarn lint

      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: yarn test --collectCoverage=true
      - store_artifacts:
          path: coverage

workflows:
  build_and_test:
    jobs:
      - build
